version: '2'
services:
    apache:
        build: apache
        container_name: apache
        ports:
          - 80:80
        volumes:
          - /home/gponty/docker/stack/apaphp/apache/vhosts:/etc/apache2/sites-enabled
          - /home/gponty/docker/www:/var/www
        depends_on:
          - php
          - mysql
        restart: always

    php:
        build: php
        container_name: php
        volumes:
          - /home/gponty/docker/www:/var/www
        environment:
          - maildev_host=maildev
          - PHP_IDE_CONFIG=serverName=docker-server
          - XDEBUG_CONFIG=remote_host=192.168.1.47 remote_port=9001
        depends_on:
          - maildev
          - mysql
        restart: always

    maildev:
        image: djfarrelly/maildev
        container_name: maildev
        ports:
          - 8001:80
        restart: always

    mysql:
      container_name: mysql
      image: mysql
      ports:
        - 3306:3306
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_USER=root
      volumes:
        - /home/gponty/docker/data/mysql:/var/lib/mysql
