version: '2'

services:
  proxy:
    build: nginx/
    container_name: "portainer-proxy"
    ports:
      - "8085:80"
    networks:
      - local
    restart: always

  templates:
    image: portainer/templates
    container_name: "portainer-templates"
    restart: always
    networks:
      - local

  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
#Automatically choose 'Manage the Docker instance where Portainer is running' by adding <--host=unix:///var/run/docker.sock> to the command
    command: --templates http://templates/templates.json
    restart: always
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/gponty/docker/data/portainer:/data

  watchtower:
    image: v2tec/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    restart: always
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  local:
    driver: bridge
