version: '2'
services:
    apache:
        build: apache
        container_name: apache714
        ports:
          - 80:80
        volumes:
          - /home/gponty/docker/stack/apaphp/vhosts:/etc/apache2/sites-enabled
          - /home/gponty/docker/www:/var/www
        depends_on:
          - php
          - mysql
        restart: always

    php:
        build: php
        container_name: php714
        volumes:
          - /home/gponty/docker/www:/var/www
          - /home/gponty/.ssh:/root/.ssh
        environment:
          - maildev_host=maildev
          - PHP_IDE_CONFIG=serverName=docker-server
          - XDEBUG_CONFIG=remote_port=9001
        depends_on:
          - maildev
          - mysql
        restart: always

    maildev:
        image: djfarrelly/maildev
        container_name: maildev714
        ports:
          - 8001:80
        restart: always

    mysql:
      container_name: mysql714
      image: mysql
      ports:
        - 3306:3306
      command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      restart: always
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_USER=root
      volumes:
        - /home/gponty/docker/data/mysql:/var/lib/mysql
