version: '2'
services:
    apache:
        build: apache
        container_name: apache714
        ports:
          - 80:80
        volumes:
          - /home/gponty/docker/stack/apaphp/vhosts:/etc/apache2/sites-enabled
          - /home/gponty/docker/www:/var/www
        depends_on:
          - php
          - mysql
        restart: always

    php:
        build: php
        container_name: php714
        volumes:
          - /home/gponty/docker/www:/var/www
          - /home/gponty/.ssh:/root/.ssh
        environment:
          - maildev_host=maildev
          - PHP_IDE_CONFIG=serverName=docker-server
          - XDEBUG_CONFIG=remote_port=9001
        depends_on:
          - maildev
          - mysql
        restart: always
