version: '2'
services:

    mysql:
      container_name: mysql
      image: mysql
      ports:
        - 3306:3306
      command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      restart: always
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_USER=root
      volumes:
        - /home/gponty/docker/data/mysql:/var/lib/mysql
      networks:
        - some-net

networks:
  some-net:
    driver: bridge
